name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [latest, master, v1.300.0]
        step: [version]
        # step: [version, npmExecuteScripts]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Run action to show Project Piper version
        uses: ./
        with:
          piper-version: ${{ matrix.version }}
          step-name: ${{ matrix.step }}
          flags: "--verbose --noTelemetry"
