name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@43bd643263f2a557a37e023e538ab9f83dce92a6 # v1.1.1
