name: "Markdown"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # paths:
    #   - '**/*.md'

jobs:
  markdownlint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Markdown Linting
        uses: nosborn/github-action-markdown-cli@9b5e871c11cc0649c5ac2526af22e23525fa344d # v3.3.0
        with:
          files: .
